spring:
  http:
    encoding:
      charset: utf-8
      force: false
      enabled: false
  mvc:
    favicon:
      enabled: false
#    static-path-pattern: /resources/**
  jmx:
    enabled: false
server:
  port: 33102
  context-path: /identity-auth
  ssl:
    enabled: false
  error:
    whitelabel:
      enabled: false

management:
  port: 33103
  health:
    mail:
      enabled: false
info:
  app:
    name: "@parent.artifactId@" #从pom.xml中获取
    description: "@project.description@"
    version: "@project.version@"
    spring-boot-version: "@spring.boot.version@"